config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'hospital#home'


  resources :certificates, path: 'certificates'
  resources :receivings, path: 'receivings'
  resources :doctors, path: 'doctors'
  resources :patients, path: 'patients'
  resources :hospitals, path: 'hospitals'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/receiving.rb
class Receiving < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
end

app/controllers/receivings_controller.rb
class ReceivingsController < ApplicationController
  before_action :set_receiving, only: [:show, :edit, :update, :destroy]

  # GET /receivings
  # GET /receivings.json
  def index
    @receivings = Receiving.all
  end

  # GET /receivings/1
  # GET /receivings/1.json
  def show
  end

  # GET /receivings/new
  def new
    @receiving = Receiving.new
  end

  # GET /receivings/1/edit
  def edit
  end

  # POST /receivings
  # POST /receivings.json
  def create
    @receiving = Receiving.new(receiving_params)

    respond_to do |format|
      if
      Receiving.find_by_date(@receiving.date) == nil || Receiving.find_by_time(@receiving.time) == nil ||
      Receiving.find_by_patient_id(@receiving.patient_id) == nil || Receiving.find_by_doctor_id(@receiving.doctor_id) == nil
      @receiving.save
        format.html { redirect_to receivings_url, notice: 'Receiving was successfully created.' }
        format.json { render :show, status: :created, location: @receiving }
      else
        format.html { render :new }
        format.json { render json: @receiving.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receivings/1
  # PATCH/PUT /receivings/1.json
  def update
    respond_to do |format|
      if @receiving.update(receiving_params)
        format.html { redirect_to receivings_url, notice: 'Receiving was successfully updated.' }
        format.json { render :show, status: :ok, location: @receiving }
      else
        format.html { render :edit }
        format.json { render json: @receiving.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receivings/1
  # DELETE /receivings/1.json
  def destroy
    @receiving.destroy
    respond_to do |format|
      format.html { redirect_to receivings_url, notice: 'Receiving was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receiving
      @receiving = Receiving.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receiving_params
      params.fetch(:receiving).permit(:date, :time, :patient_id, :doctor_id)
    end
end

app/helpers/receivings_helper.rb
module ReceivingsHelper
end

app/views/receivings/_form.html.erb
<%= form_with(model: receiving, local: true) do |form| %>
  <% if receiving.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receiving.errors.count, "error") %> prohibited this receiving from being saved:</h2>

      <ul>
        <% receiving.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Дата прийому' %>
    <%= form.text_field :date,
                        :size => '30',
                        #:pattern => '\d{1,9}$',
                        :placeholder => "Введіть дату",
                        required: true %>
  </div>

  <div class="field">
    <%= form.label 'Час прийому' %>
    <%= form.text_field :time,
                        :size => '30',
                        #:pattern => '\d{1,9}$',
                        :placeholder => "Введіть час",
                        required: true %>
  </div>

  <div class="field">
    <%= form.label 'Пацієнт' %>
    <%= form.collection_select :patient_id,
                               Patient.order(:name),:id,:name, include_blank: false %>
  </div>

  <div class="field">
    <%= form.label 'Лікар' %>
    <%= form.collection_select :doctor_id,
                               Doctor.order(:name),:id,:name, include_blank: false %>
  </div>

  <div class="actions">
    <%= form.submit('Підтвердити', {:class => 'btn btn-success'}) %>
  </div>
<% end %>

app/views/receivings/edit.html.erb
<h1>Редагування запису до лікаря</h1>

<%= render 'form', receiving: @receiving %>

<%= link_to 'Назад', receivings_path %>

app/views/receivings/index.html.erb
<br>
<%#= link_to 'Лікарі', doctors_path %>
<%#= link_to 'Пацієнти', patients_path %>
<%#= link_to 'Запис на прийом', receivings_path %>
<%#= link_to 'Створити довідку', certificates_path %>
<%#= link_to "Вийти", '/logout', method: :get%>

<p id="notice"><%= notice %></p>

<h1>Запис на прийом</h1>
<%= link_to 'Створити запис', new_receiving_path %>
<table border="1">
<!--  <thead>-->
<!--    <tr>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

  <tbody>
    <% @receivings.each do |receiving| %>
      <tr>
        <td><%= receiving.date %></td>
        <td><%= receiving.time %></td>
        <td><%= receiving.patient.name %></td>
        <td><%= receiving.doctor.name %></td>
<!--        <td><%#= link_to 'Переглянути', receiving %></td>-->
        <td><%= link_to 'Редагувати', edit_receiving_path(receiving) %></td>
        <% if current_user && current_user.admin %>
        <td><%= link_to 'Видалити', receiving, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/receivings/new.html.erb
<h1>Новий запис до лікаря</h1>

<%= render 'form', receiving: @receiving %>

<%= link_to 'Назад', receivings_path %>

app/views/receivings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Редагувати', edit_receiving_path(@receiving) %> |
<%= link_to 'Назад', receivings_path %>