config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'hospital#home'


  resources :certificates, path: 'certificates'
  resources :receivings, path: 'receivings'
  resources :doctors, path: 'doctors'
  resources :patients, path: 'patients'
  resources :hospitals, path: 'hospitals'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if
      Patient.find_by_name(@patient.name) == nil ||
          Patient.find_by_phone(@patient.phone) == nil ||
          Patient.find_by_birth_date(@patient.birth_date) == nil
      @patient.save
        format.html { redirect_to patients_url }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patients_url, notice: 'Пацієнт оновленний.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    if @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Пацієнт видаленний.' }
      format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.fetch(:patient).permit(:name, :phone, :birth_date, :diagnosis)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="field">
  <%= form.label 'ПІП' %>
  <%= form.text_field :name,
                      :size => '30',
                      #:pattern => '\d{1,9}$',
                      :placeholder => "Введіть ПІП",
                      required: true %>
</div>

<div class="field">
  <%= form.label 'Номер телефону' %>
  <%= form.text_field :phone,
                      :size => '30',
                      #:pattern => '\d{1,9}$',
                      :placeholder => "Введіть номер телефону",
                      required: true %>
</div>

<div class="field">
  <%= form.label 'Дата народження' %>
  <%= form.text_field :birth_date,
                      :size => '30',
                      #:pattern => '.{1,10}',
                      :placeholder => "Введіть дату народження",
                      required: true %>
</div>

<div class="field">
  <%= form.label 'Діагноз' %>
  <%= form.text_area :diagnosis,
                      :size => '30',
                      #:pattern => '.{1,10}',
                      :placeholder => "Введіть діагноз",
                      required: false %>
</div>

<div class="actions">
  <%= form.submit('Підтвердити', {:class => 'btn btn-success'}) %>
</div>
<% end %>

app/views/patients/edit.html.erb
<h1>Редагування інформації про пацієнта</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Назад', patients_path %>

app/views/patients/index.html.erb
<br>
<%#= link_to 'Лікарі', doctors_path %>
<%#= link_to 'Пацієнти', patients_path %>
<%#= link_to 'Запис на прийом', receivings_path %>
<%#= link_to 'Створити довідку', certificates_path %>
<%#= link_to "Вийти", '/logout', method: :get%>

<p id="notice"><%= notice %></p>

<h1>Пацієнти</h1>
<%= link_to 'Створити пацієнта', new_patient_path %>
<table border="1">
<!--  <thead>-->
<!--    <tr>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.birth_date %></td>
        <td><%= patient.diagnosis %></td>
<!--        <td><%#= link_to 'Переглянути', patient %></td>-->
        <td><%= link_to 'Редагувати', edit_patient_path(patient) %></td>
        <% if current_user && current_user.admin %>
        <td><%= link_to 'Видалити', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/patients/new.html.erb
<h1>Особиста інформація пацієнта</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Назад', patients_path %>

app/views/patients/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<%= link_to 'Редагувати', edit_patient_path(@patient) %> |
<%= link_to 'Назад', patients_path %>