config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'hospital#home'


  resources :certificates, path: 'certificates'
  resources :receivings, path: 'receivings'
  resources :doctors, path: 'doctors'
  resources :patients, path: 'patients'
  resources :hospitals, path: 'hospitals'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :receivings
  has_many :certificates
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @doctors = Doctor.all
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if
      Doctor.find_by_name(@doctor.name) == nil ||
          Doctor.find_by_phone(@doctor.phone) == nil ||
          Doctor.find_by_specialty(@doctor.specialty) == nil
      @doctor.save
        format.html { redirect_to doctors_url, notice: 'Лікар створенй.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctors_url, notice: 'Лікар оновлений.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        #format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    if
    #Doctor.find_by_doctor_id(@recevings.doctor_id) == nil ||
    #    Doctor.find_by_doctor_id(@certificstes.doctor_id) == nil

    @doctor.destroy
    end
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Лікар видаленний.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.fetch(:doctor).permit(:name, :phone, :specialty)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'ПІП' %>
    <%= form.text_field :name,
                        :size => '30',
                        #:pattern => '\d{1,9}$',
                        :placeholder => "Введіть ПІП",
                        required: true %>
  </div>

  <div class="field">
    <%= form.label 'Номер телефону' %>
    <%= form.text_field :phone,
                        :size => '30',
                        #:pattern => '\d{1,9}$',
                        :placeholder => "Введіть номер телефону",
                        required: true %>
  </div>

  <div class="field">
    <%= form.label 'Фах' %>
    <%= form.text_field :specialty,
                        :size => '30',
                        #:pattern => '.{1,10}',
                        :placeholder => "Введіть фах",
                        required: true %>
  </div>

  <div class="actions">
    <%= form.submit('Підтвердити', {:class => 'btn btn-success'}) %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Редагування лікаря</h1>

<%= render 'form', doctor: @doctor %>

<%#= link_to 'Переглянути', @doctor %>
<%= link_to 'Назад', doctors_path %>

app/views/doctors/index.html.erb
<br>

<%#= link_to 'Лікарі', doctors_path %>
<%#= link_to 'Пацієнти', patients_path %>
<%#= link_to 'Запис на прийом', receivings_path %>
<%#= link_to 'Створити довідку', certificates_path %>
<%#= link_to 'Вийти', destroy_user_session_path, method: :delete %>

<p id="notice"><%= notice %></p>

<h1>Лікарі</h1>
<%= link_to 'Створити лікаря', new_doctor_path %>
<table border="1">
<!--  <thead>-->
<!--    <tr>-->
<!--      <th colspan="2"></th>-->
<!--    </tr>-->
<!--  </thead>-->

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.phone %></td>
        <td><%= doctor.specialty %></td>
<!--        <td><%#= link_to 'Переглянути', doctor %></td>-->
        <td><%= link_to 'Редагувати', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Видалити', doctor, method: :delete, data: { confirm: 'Ви впевнені?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'Новий лікар', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>Додавання лікаря</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Назад', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Редагувати', edit_doctor_path(@doctor) %> |
<%= link_to 'Назад', doctors_path %>