config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'hospital#home'


  resources :certificates, path: 'certificates'
  resources :receivings, path: 'receivings'
  resources :doctors, path: 'doctors'
  resources :patients, path: 'patients'
  resources :hospitals, path: 'hospitals'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  before_action :set_certificate, only: [:show, :edit, :update, :destroy]

#  respond_to :docx
#  def my_action
#  respond_with(@object, content: '<html><head></head><body><p>Hello</p></body></html>', filename: 'my_file.docx')
#end
  # GET /certificates
  # GET /certificates.json
  def index
    @certificates = Certificate.all
  end

  # GET /certificates/1
  # GET /certificates/1.json
  def show
  end

  # GET /certificates/new
  def new
    @certificate = Certificate.new
  end

  # GET /certificates/1/edit
  def edit
  end

  # POST /certificates
  # POST /certificates.json
  def create
    @certificate = Certificate.new(certificate_params)

    respond_to do |format|
      if
      Certificate.find_by_patient_id(@certificate.patient_id) == nil || Certificate.find_by_doctor_id(@certificate.doctor_id) == nil ||
      Certificate.find_by_income_date(@certificate.income_date) == nil || Certificate.find_by_discharge_date(@certificate.discharge_date) == nil
      @certificate.save
        format.html { redirect_to certificates_url, notice: 'Довідка створена.' }
        format.json { render :show, status: :created, location: @certificate }
      else
        format.html { render :new }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificates/1
  # PATCH/PUT /certificates/1.json
  def update
    respond_to do |format|
      if @certificate.update(certificate_params)
        format.html { redirect_to certificates_url, notice: 'Довідка редагована.' }
        format.json { render :show, status: :ok, location: @certificate }
      else
        format.html { render :edit }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificates/1
  # DELETE /certificates/1.json
  def destroy
    @certificate.destroy
    respond_to do |format|
      format.html { redirect_to certificates_url, notice: 'Довідка видалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certificate
      @certificate = Certificate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certificate_params
      params.fetch(:certificate).permit(:patient_id, :doctor_id, :income_date, :discharge_date)
    end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_form.html.erb
<%= form_with(model: certificate, local: true) do |form| %>
  <% if certificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(certificate.errors.count, "error") %> prohibited this certificate from being saved:</h2>

      <ul>
        <% certificate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Пацієнт' %>
    <%= form.collection_select :patient_id,
                               Patient.order(:name),:id,:name, include_blank: false %>
  </div>

  <div class="field">
    <%= form.label 'Лікар' %>
    <%= form.collection_select :doctor_id,
                               Doctor.order(:name),:id,:name, include_blank: false %>
  </div>

  <div class="field">
    <%= form.label 'Дата надходження' %>
    <%= form.text_field :income_date,
                        :size => '30',
                        #:pattern => '\d{1,9}$',
                        :placeholder => "Введіть дату",
                        required: true %>
  </div>

  <div class="field">
    <%= form.label 'Дата виписки' %>
    <%= form.text_field :discharge_date,
                        :size => '30',
                        #:pattern => '\d{1,9}$',
                        :placeholder => "Введіть дату",
                        required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/certificates/edit.html.erb
<h1>Editing Certificate</h1>

<%= render 'form', certificate: @certificate %>

<%= link_to 'Переглянути', @certificate %> |
<%= link_to 'Назад', certificates_path %>

app/views/certificates/index.html.erb
<br>
<%#= link_to 'Лікарі', doctors_path %>
<%#= link_to 'Пацієнти', patients_path %>
<%#= link_to 'Запис на прийом', receivings_path %>
<%#= link_to 'Створити довідку', certificates_path %>
<%#= link_to "Вийти", '/logout', method: :get%>

<p id="notice"><%= notice %></p>

<h1>Довідки</h1>
<%= link_to 'Створити довідку', new_certificate_path %>
<table border="1">
<!--  <thead>-->
<!--    <tr>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

  <tbody>
    <% @certificates.each do |certificate| %>
      <tr>
        <td><%= certificate.patient.name%></td>
        <td><%= certificate.doctor.name%></td>
        <td><%= certificate.income_date%></td>
        <td><%= certificate.discharge_date%></td>
<!--        <td><%#= link_to 'Переглянути', certificate %></td>-->
        <td><%= link_to 'Редагувати', edit_certificate_path(certificate) %></td>
        <td><%= link_to 'Видалити', certificate, method: :delete, data: { confirm: 'Ви впевнені?' } %></td>
<!--        <td><%#= link_to 'Завантажити', my_action_certificate_path %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/certificates/new.html.erb
<h1>New Certificate</h1>
<%= render 'form', certificate: @certificate %>

<%= link_to 'Назад', certificates_path %>

app/views/certificates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Редагувати', edit_certificate_path(@certificate) %> |
<%= link_to 'Назад', certificates_path %>